---   
- hosts: all
  become: yes
  tasks:
  - name: install packages
    yum: 
      name: 
        - http://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        - epel-release
      state: present
      update_cache: true
  - name: install Postgresql14
    yum:
      name: 
        - postgresql14-server
        - postgresql14
        - policycoreutils-python
        - python-pip
        - python-setuptools
      state: present
      update_cache: true
  - name: Install pexpect
    pip:
      name: pexpect
  - name: check init 
    stat:
      path: /var/lib/pgsql/14/data/pg_stat
    register: stat_result
  - name: init db
    shell: postgresql-14-setup initdb
    when: not stat_result.stat.exists and ansible_hostname == 'master'
  - name: 
    template: 
      src: "{{ item }}" 
      dest: /var/lib/pgsql/14/data/
      owner: postgres 
      group: postgres
      mode: 0600
    with_fileglob:
      - templates/*.conf
  - name: start postgresql
    systemd:
      name: postgresql-14
      enabled: yes
      state: restarted      
  - name: create repl user
    expect: 
      command: su - postgres -c "createuser --replication -P repluser"
      timeout: null
      responses: 
        '.*Enter password .*': "12345678q"
        '.*Enter it.*': "12345678q" 
    when: ansible_hostname == 'master'
  - name: restart network on master
    systemd:
      name: network
      state: restarted  
    when: ansible_hostname == 'master'
  - name: create basebackup
    expect: 
      command: su - postgres -c "pg_basebackup --host=192.168.11.150 --username=repluser --pgdata=/var/lib/pgsql/14/data --wal-method=stream --write-recovery-conf"
      timeout: null
      responses: 
        '.*Password.*': "12345678q"
    when: ansible_hostname == 'slave'
